language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.0
os:
  - linux
install:
  - bundle install
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
services:
  - postgresql
script: bundle exec rake test
